// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyouqmuhnzoxqsmskztp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5b3VxbXVobnpveHFzbXNrenRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTgwNjgsImV4cCI6MjA2MzczNDA2OH0.UjwSyLoSVM8lYpEeIAgGPEVL8bCJwlC6phyK3G7_nk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);